// Generated by minibufc

const floatPrecision = 3;

export interface SystemData {
  topTemp: number;
  bottomTemp: number;
  powerSupplyTemp: number;
  topHeaterActive: boolean;
  bottomHeaterActive: boolean;
  powerSupplyVoltage: number;
  proximityActive: boolean;
  pedalActive: boolean;
  coolingFanActive: boolean;
  pressureValveActive: boolean;
  weldingTime: number;
  coolingTime: number;
}

export interface SystemVersion {
  major: number;
  minor: number;
  patch: number;
}

export interface SystemConfig {
  opTime: number;
  coTime: number;
  topTempThreshold: number;
  bottomTempThreshold: number;
  temp1Offset: number;
  temp2Offset: number;
  menuResetDelay: number;
  timeCalibration: number;
  maxTempError: number;
  vccVoltageError: number;
  powerTempError: number;
  powerVccErrorEnabled: boolean;
  sysErrorEnabled: boolean;
  voltageCalibration: number;
  heaterErrorEnable: number;
  coolingDelay: number;
  useInternalADC: boolean;
}

export function SystemDataParse(str: string): SystemData {
  const start = str.indexOf('[');
  if (start === -1) throw new Error('Invalid format');
  const end = str.indexOf(']', start);
  if (end === -1) throw new Error('Invalid format');
  const count = parseInt(str.slice(start + 1, end));
  const values = str.slice(end + 1).split(';');
  const result: SystemData = {
    topTemp: 0.0,
    bottomTemp: 0.0,
    powerSupplyTemp: 0.0,
    topHeaterActive: false,
    bottomHeaterActive: false,
    powerSupplyVoltage: 0.0,
    proximityActive: false,
    pedalActive: false,
    coolingFanActive: false,
    pressureValveActive: false,
    weldingTime: 0,
    coolingTime: 0,
  };
  for (let i = 0; i < Math.min(count, values.length); i++) {
    if (i === 0) {
      result.topTemp = parseFloat(values[i]);
    }
    if (i === 1) {
      result.bottomTemp = parseFloat(values[i]);
    }
    if (i === 2) {
      result.powerSupplyTemp = parseFloat(values[i]);
    }
    if (i === 3) {
      result.topHeaterActive = values[i] === 'T';
    }
    if (i === 4) {
      result.bottomHeaterActive = values[i] === 'T';
    }
    if (i === 5) {
      result.powerSupplyVoltage = parseFloat(values[i]);
    }
    if (i === 6) {
      result.proximityActive = values[i] === 'T';
    }
    if (i === 7) {
      result.pedalActive = values[i] === 'T';
    }
    if (i === 8) {
      result.coolingFanActive = values[i] === 'T';
    }
    if (i === 9) {
      result.pressureValveActive = values[i] === 'T';
    }
    if (i === 10) {
      result.weldingTime = parseInt(values[i]);
    }
    if (i === 11) {
      result.coolingTime = parseInt(values[i]);
    }
  }
  return result;
}

export function SystemDataSerialize(obj: SystemData): string {
  const count = 12;
  let str = `[${count}]`;
  str += `${obj.topTemp.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.bottomTemp.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.powerSupplyTemp.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.topHeaterActive ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.bottomHeaterActive ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.powerSupplyVoltage.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.proximityActive ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.pedalActive ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.coolingFanActive ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.pressureValveActive ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.weldingTime}`;
  str += ';';
  str += `${obj.coolingTime}`;
  return str;
}

export function SystemVersionParse(str: string): SystemVersion {
  const start = str.indexOf('[');
  if (start === -1) throw new Error('Invalid format');
  const end = str.indexOf(']', start);
  if (end === -1) throw new Error('Invalid format');
  const count = parseInt(str.slice(start + 1, end));
  const values = str.slice(end + 1).split(';');
  const result: SystemVersion = {
    major: 0,
    minor: 0,
    patch: 0,
  };
  for (let i = 0; i < Math.min(count, values.length); i++) {
    if (i === 0) {
      result.major = parseInt(values[i]);
    }
    if (i === 1) {
      result.minor = parseInt(values[i]);
    }
    if (i === 2) {
      result.patch = parseInt(values[i]);
    }
  }
  return result;
}

export function SystemVersionSerialize(obj: SystemVersion): string {
  const count = 3;
  let str = `[${count}]`;
  str += `${obj.major}`;
  str += ';';
  str += `${obj.minor}`;
  str += ';';
  str += `${obj.patch}`;
  return str;
}

export function SystemConfigParse(str: string): SystemConfig {
  const start = str.indexOf('[');
  if (start === -1) throw new Error('Invalid format');
  const end = str.indexOf(']', start);
  if (end === -1) throw new Error('Invalid format');
  const count = parseInt(str.slice(start + 1, end));
  const values = str.slice(end + 1).split(';');
  const result: SystemConfig = {
    opTime: 0,
    coTime: 0,
    topTempThreshold: 0,
    bottomTempThreshold: 0,
    temp1Offset: 0.0,
    temp2Offset: 0.0,
    menuResetDelay: 0,
    timeCalibration: 0.0,
    maxTempError: 0.0,
    vccVoltageError: 0.0,
    powerTempError: 0.0,
    powerVccErrorEnabled: false,
    sysErrorEnabled: false,
    voltageCalibration: 0.0,
    heaterErrorEnable: 0.0,
    coolingDelay: 0,
    useInternalADC: false,
  };
  for (let i = 0; i < Math.min(count, values.length); i++) {
    if (i === 0) {
      result.opTime = parseInt(values[i]);
    }
    if (i === 1) {
      result.coTime = parseInt(values[i]);
    }
    if (i === 2) {
      result.topTempThreshold = parseInt(values[i]);
    }
    if (i === 3) {
      result.bottomTempThreshold = parseInt(values[i]);
    }
    if (i === 4) {
      result.temp1Offset = parseFloat(values[i]);
    }
    if (i === 5) {
      result.temp2Offset = parseFloat(values[i]);
    }
    if (i === 6) {
      result.menuResetDelay = parseInt(values[i]);
    }
    if (i === 7) {
      result.timeCalibration = parseFloat(values[i]);
    }
    if (i === 8) {
      result.maxTempError = parseFloat(values[i]);
    }
    if (i === 9) {
      result.vccVoltageError = parseFloat(values[i]);
    }
    if (i === 10) {
      result.powerTempError = parseFloat(values[i]);
    }
    if (i === 11) {
      result.powerVccErrorEnabled = values[i] === 'T';
    }
    if (i === 12) {
      result.sysErrorEnabled = values[i] === 'T';
    }
    if (i === 13) {
      result.voltageCalibration = parseFloat(values[i]);
    }
    if (i === 14) {
      result.heaterErrorEnable = parseFloat(values[i]);
    }
    if (i === 15) {
      result.coolingDelay = parseInt(values[i]);
    }
    if (i === 16) {
      result.useInternalADC = values[i] === 'T';
    }
  }
  return result;
}

export function SystemConfigSerialize(obj: SystemConfig): string {
  const count = 17;
  let str = `[${count}]`;
  str += `${obj.opTime}`;
  str += ';';
  str += `${obj.coTime}`;
  str += ';';
  str += `${obj.topTempThreshold}`;
  str += ';';
  str += `${obj.bottomTempThreshold}`;
  str += ';';
  str += `${obj.temp1Offset.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.temp2Offset.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.menuResetDelay}`;
  str += ';';
  str += `${obj.timeCalibration.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.maxTempError.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.vccVoltageError.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.powerTempError.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.powerVccErrorEnabled ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.sysErrorEnabled ? 'T' : 'F'}`;
  str += ';';
  str += `${obj.voltageCalibration.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.heaterErrorEnable.toFixed(floatPrecision)}`;
  str += ';';
  str += `${obj.coolingDelay}`;
  str += ';';
  str += `${obj.useInternalADC ? 'T' : 'F'}`;
  return str;
}

